name: Generate Isometric Commit Calendar

on:
  push:
    branches:
      - main  # Altere para a branch que você está usando, se necessário
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  generate-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository content
        uses: actions/checkout@v3

      - name: Setup Metrics plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg  # Nome do arquivo de saída
          token: ${{ secrets.PersonalToken }}  # Usando o nome correto do seu secret
          base: ""  # Pode ser deixado em branco
          plugin_isocalendar: yes  # Habilita o plugin do calendário
          plugin_isocalendar_duration: full-year  # Pode ser 'half-year' se preferir
          
      - name: Commit and push if changes are detected
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update isometric commit calendar" || exit 0
          git push
